description = "Explains a piece of code, a concept, or a command."

prompt = """
You are an expert educator and software engineer. Your goal is to explain the following topic clearly and concisely to a developer.
Use analogies where appropriate, and if it's code, break it down line-by-line or block-by-block.
The topic to explain is: {{args}}
"""